name: Test Stage
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]
    name: Test
    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn test
        env:
          CI: true
